### ISSUE TITLE
Handle errors when trying to copy items

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/ExchangeLogCollector#128]
Seeing the following issue that prevents the script from finishing. 

```
[server3 - Script Debug] : Found 1 number of files at the location D:\Program Files\Microsoft\Exchange Server\V15\Bin\Search\Ceres\Diagnostics\ETLTraces
[server3 - Script Debug] : Calling: Test-FreeSpace
[server3 - Script Debug] : Calling: Get-ItemsSize
[server3] : An error occurred in Remote-Functions
[server3] : Error Exception: System.UnauthorizedAccessException: Access is denied ---> System.ComponentModel.Win32Exception: Access is denied
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.Commands.FileSystemProvider.ItemExists(String path, ErrorRecord& error)
[server3] : Error Stack: at Get-ItemsSize, C:\ExchangeLogCollector.ps1: line 1850
```

**Comment by dpaulson45** [comment]
In a lab server that wasn't part of a DAG and we try to collect Failover cluster logs gets the following error

```
[SOLO-E19A] : Creating Directory: C:\MS_Logs_Collection\2021110\SOLO-E19A\Windows_Event_Logs\Microsoft-Windows-FailoverClustering
[SOLO-E19A] : An error occurred in Invoke-RemoteFunctions
[SOLO-E19A] : Error Exception: System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'FilePaths' because it is an empty collection.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at Microsoft.PowerShell.Commands.InvokeExpressionCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
[SOLO-E19A] : Error Stack: at Copy-BulkItems, C:\Users\Kylo\Desktop\ExchangeLogCollector.ps1: line 2310
at Save-WindowsEventLogs, C:\Users\Kylo\Desktop\ExchangeLogCollector.ps1: line 2735
at <ScriptBlock>, <No file>: line 1
at Invoke-RemoteMain, C:\Users\Kylo\Desktop\ExchangeLogCollector.ps1: line 3380
at Invoke-RemoteFunctions, C:\Users\Kylo\Desktop\ExchangeLogCollector.ps1: line 3396
at Main, C:\Users\Kylo\Desktop\ExchangeLogCollector.ps1: line 3512
at <ScriptBlock>, C:\Users\Kylo\Desktop\ExchangeLogCollector.ps1: line 3521
at <ScriptBlock>, <No file>: line 1
```
