### ISSUE TITLE
Collect Failover Metrics can get the following result

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/ExchangeLogCollector#167]
Need to make sure we handle this better.

```
[VNEXT-E19TOOLS] : Attempting to run CollectOverMetrics.ps1 against E19DAG1
Get statistics from VNext-E19B.VNext.local
Get statistics from VNext-E19A.VNext.local
Found total of 0 entries

Generated the following per-DAG reports:
C:\MS_Logs_Collection\202125\VNEXT-E19TOOLS\Temp_Exchange_Failover_Reports\E19DAG1_FailoverMetrics\FailoverReport.E19DAG1.2021_02_05_15_00_55.csv

Importing data from C:\MS_Logs_Collection\202125\VNEXT-E19TOOLS\Temp_Exchange_Failover_Reports\E19DAG1_FailoverMetrics\FailoverReport.E19DAG1.2021_02_05_15_00_55.csv

Generating summary report
[VNEXT-E19TOOLS - Script Debug] : Failed to collect failover metrics
[VNEXT-E19TOOLS - Script Debug] : Error Exception: System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Data' because it is null.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
[VNEXT-E19TOOLS - Script Debug] : Error Stack: at <ScriptBlock>, C:\Program Files\Microsoft\Exchange Server\V15\Scripts\CollectOverMetrics.ps1: line 1500
at <ScriptBlock>, C:\Users\David\Desktop\ExchangeLogCollector.ps1: line 1073
at Write-LargeDataObjectsOnMachine, C:\Users\David\Desktop\ExchangeLogCollector.ps1: line 1063
at Main, C:\Users\David\Desktop\ExchangeLogCollector.ps1: line 4016
at <ScriptBlock>, C:\Users\David\Desktop\ExchangeLogCollector.ps1: line 4052
at <ScriptBlock>, <No file>: line 1
[VNEXT-E19TOOLS - Script Debug] : Not compressing or copying over this folder.
[VNEXT-E19TOOLS - Script Debug] : Function Enter: Get-ExchangeBasicServerObject
```

**Comment by dpaulson45** [comment]
Here there isn't actually any data, so don't care if we copy the data over.
