### ISSUE TITLE
Error in Remote Functions - Get-Volume

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/ExchangeLogCollector#61]
After adding Get-Volume into the ServerInfo switch, it is failing on Exchange 2010 Windows Server 2008 R2 because the cmdlet doesn't exist. 

[NFL-E2K10AIO1] : An error occurred in Remote-Functions
Error Exception: System.Management.Automation.CommandNotFoundException: The term 'Get-Volume' is not recognized as the n
ame of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandOrigin commandOrigin)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrig
in, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command)
   at System.Management.Automation.CommandNode.CreateCommandProcessor(Int32& index, ExecutionContext context)
   at System.Management.Automation.CommandNode.AddToPipeline(PipelineProcessor pipeline, ExecutionContext context)
   at System.Management.Automation.PipelineNode.Execute(Array input, Pipe outputPipe, ArrayList& resultList, ExecutionCo
ntext context)
   at System.Management.Automation.ParseTreeNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.AssignmentStatementNode.Execute(Array input, Pipe outputPipe, ExecutionContext contex
t)
   at System.Management.Automation.StatementListNode.ExecuteStatement(ParseTreeNode statement, Array input, Pipe outputP
ipe, ArrayList& resultList, ExecutionContext context)
Error Stack:

**Comment by dpaulson45** [comment]
Addressed in commit f8abc84a4be4cddb1560854a1f2513f208a3315f
